import { WeightedOptions } from '@utils/rng/weighted-options';
import { TableRoller } from '@utils/table-roller';

// DMG page 144
export const magicItemTableB = new TableRoller<string>({
  options: new WeightedOptions([
    { weight: 15, data: 'Potion of greater healing' },
    { weight: 7, data: 'Potion of fire breath' },
    { weight: 7, data: 'Potion of resistance' },
    { weight: 5, data: 'Ammunition, +1' },
    { weight: 5, data: 'Potion of animal friendship' },
    { weight: 5, data: 'Potion of hill giant strength' },
    { weight: 5, data: 'Potion of growth' },
    { weight: 5, data: 'Potion of water breathing' },
    { weight: 5, data: 'Spell scroll (2nd level)' },
    { weight: 5, data: 'Spell scroll (3rd level)' },
    { weight: 3, data: 'Bag of holding' },
    { weight: 3, data: `Keoghtom's ointment` },
    { weight: 3, data: 'Oil of slipperiness' },
    { weight: 2, data: 'Dust of disappearance' },
    { weight: 2, data: 'Dust of dryness' },
    { weight: 2, data: 'Dust of sneezing and choking' },
    { weight: 2, data: 'Elemental gem' },
    { weight: 2, data: 'Philter of love' },
    { weight: 1, data: 'Alchemy jug' },
    { weight: 1, data: 'Cap of water breathing' },
    { weight: 1, data: 'Cloak of the manta ray' },
    { weight: 1, data: 'Driftglobe' },
    { weight: 1, data: 'Goggles of night' },
    { weight: 1, data: 'Helm of comprehending languages' },
    { weight: 1, data: 'Immovable rod' },
    { weight: 1, data: 'Lantern of revealing' },
    { weight: 1, data: `Mariner's armor` },
    { weight: 1, data: 'Mithral armor' },
    { weight: 1, data: 'Potion of poison' },
    { weight: 1, data: 'Ring of swimming' },
    { weight: 1, data: 'Robe of useful items' },
    { weight: 1, data: 'Rope of climbing' },
    { weight: 1, data: 'Saddle of the cavalier' },
    { weight: 1, data: 'Wand of magic detection' },
    { weight: 1, data: 'Wand of secrets' },
  ]),
});
