import { WeightedOptions } from '@utils/rng/weighted-options';
import { TableRoller } from '@utils/table-roller';

// DMG page 146
export const magicItemTableF = new TableRoller<string>({
  options: new WeightedOptions([
    { weight: 15, data: 'Weapon, +1' },
    { weight: 3, data: 'Shield, +1' },
    { weight: 3, data: 'Sentinel shield' },
    {
      weight: 2,
      data: 'Amulet of proof against detection and location',
    },
    { weight: 2, data: 'Boots of elvenkind' },
    { weight: 2, data: 'Boots of striding and springing' },
    { weight: 2, data: 'Bracers of archery' },
    { weight: 2, data: 'Brooch of shielding' },
    { weight: 2, data: 'Broom of flying' },
    { weight: 2, data: 'Cloak of elvenkind' },
    { weight: 2, data: 'Cloak of protection' },
    { weight: 2, data: 'Gauntlets of ogre power' },
    { weight: 2, data: 'Hat of disguise' },
    { weight: 2, data: 'Javelin of ligtning' },
    { weight: 2, data: 'Pearl of power' },
    { weight: 2, data: 'Rod of the pact keeper, +1' },
    { weight: 2, data: 'Slippers of spider climbing' },
    { weight: 2, data: 'Staff of the adder' },
    { weight: 2, data: 'Staff of the python' },
    { weight: 2, data: 'Sword of vengeance' },
    { weight: 2, data: 'Trident of fish command' },
    { weight: 2, data: 'Wand of magic missiles' },
    { weight: 2, data: 'Wand of the war mage, +1' },
    { weight: 2, data: 'Wand of web' },
    { weight: 2, data: 'Weapon of warning' },
    { weight: 1, data: 'Adamantine armor (chain mail)' },
    { weight: 1, data: 'Adamantine armor (chain shirt)' },
    { weight: 1, data: 'Adamantine armor (scale mail)' },
    { weight: 1, data: 'Bag of tricks (gray)' },
    { weight: 1, data: 'Bga of tricks (rust)' },
    { weight: 1, data: 'Bga of tricks (tan)' },
    { weight: 1, data: 'Boots of the winterlands' },
    { weight: 1, data: 'Circlet of blasting' },
    { weight: 1, data: 'Deck of illusions' },
    { weight: 1, data: 'Eversmoking bottle' },
    { weight: 1, data: 'Eyes of charming' },
    { weight: 1, data: 'Eyes of the eagle' },
    { weight: 1, data: 'Figurine of wondrous power (silver raven)' },
    { weight: 1, data: 'Gem of brightness' },
    { weight: 1, data: 'Gloves of missile snaring' },
    { weight: 1, data: 'Gloves of swimming and climbing' },
    { weight: 1, data: 'Gloves of thievery' },
    { weight: 1, data: 'Headband of intellect' },
    { weight: 1, data: 'Helm of telepathy' },
    { weight: 1, data: 'Instrument of the bards (Doss lute)' },
    { weight: 1, data: 'Instrument of the bards (Fochlucan bandore)' },
    {
      weight: 1,
      data: 'Instrument of the bards (Mac-Fuimidh cittern)',
    },
    { weight: 1, data: 'Medallion of thoughts' },
    { weight: 1, data: 'Necklace of adaptation' },
    { weight: 1, data: 'Periapt of wound closure' },
    { weight: 1, data: 'Pipes of haunting' },
    { weight: 1, data: 'Pipes of the sewers' },
    { weight: 1, data: 'Ring of jumping' },
    { weight: 1, data: 'Ring of mind shielding' },
    { weight: 1, data: 'Ring of warmth' },
    { weight: 1, data: 'Ring of water walking' },
    { weight: 1, data: 'Quiver of Ehlonna' },
    { weight: 1, data: 'Stone of good luck' },
    { weight: 1, data: 'Wind fan' },
    { weight: 1, data: 'Winged boots' },
  ]),
});
