// XGE 190
export const romanFemale = {
  markov: true,
  list: [
    'Aelia',
    'Aemilia',
    'Agrippina',
    'Alba',
    'Antonia',
    'Aquila',
    'Augusta',
    'Aurelia',
    'Balbina',
    'Blandina',
    'Caelia',
    'Camilla',
    'Casia',
    'Claudia',
    'Cloelia',
    'Domitia',
    'Drusa',
    'Fabia',
    'Fabricia',
    'Fausta',
    'Flavia',
    'Floriana',
    'Fulvia',
    'Germana',
    'Glaucia',
    'Gratiana',
    'Hadriana',
    'Hermina',
    'Horatia',
    'Hortensia',
    'lovita',
    'lulia',
    'Laelia',
    'Laurentia',
    'Livia',
    'Longina',
    'Lucilla',
    'Lucretia',
    'Marcella',
    'Marcia',
    'Maxima',
    'Nona',
    'Octavia',
    'Paulina',
    'Petronia',
    'Porcia',
    'Tacita',
    'Tullia',
    'Verginia',
    'Vita ',
  ],
};

// XGE 190
export const romanMale = {
  markov: true,
  list: [
    'Aelius',
    'Aetius',
    'Agrippa',
    'Albanus',
    'Albus',
    'Antonius',
    'Appius',
    'Aquilinus',
    'Atilus',
    'Augustus',
    'Aurelius',
    'Avitus',
    'Balbus',
    'Blandus',
    'Blasius',
    'Brutus',
    'Caelius',
    'Caius',
    'Casian',
    'Cassius',
    'Cato',
    'Celsus',
    'Claudius',
    'Cloelius',
    'Cnaeus',
    'Crispus',
    'Cyprianus',
    'Diocletianus',
    'Egnatius',
    'Ennius',
    'Fabricius',
    'Faustus',
    'Gaius',
    'Germanus',
    'Gnaeus',
    'Horatius',
    'lovianus',
    'lulius',
    'Lucilius',
    'Manius',
    'Marcus',
    'Marius',
    'Maximus',
    'Octavius',
    'Paulus',
    'Quintilian',
    'Regulus',
    'Servius',
    'Tacitus',
    'Varius ',
  ],
};
