import { NameDefinitions } from '.';

type Type = 'child' | 'male' | 'female';
type Part = 'male' | 'female' | 'clan' | 'child';

export const dragonbornNames: NameDefinitions<Type, Part> = {
  race: 'Dragonborn',
  description: `Dragonborn have personal names given at birth,
  but they put their clan names first as a mark of
  honor. A childhood name or nickname is often used
  among clutchmates as a descriptive term or a term
  of endearment. The name might recall an event or
  center on a habit.`,
  types: {
    male: {
      description: 'Male dragonborn names',
      parts: ['male', 'clan'],
    },
    female: {
      description: 'Female dragonborn names',
      parts: ['female', 'clan'],
    },
    child: {
      description: 'Child dragonborn names',
      parts: ['child'],
    },
  },
  parts: {
    male: [
      // PHB
      'Arjhan',
      'Balasar',
      'Bharash',
      'Donaar',
      'Ghesh',
      'Heskan',
      'Kriv',
      'Medrash',
      'Mehen',
      'Nadarr',
      'Pandjed',
      'Patrin',
      'Rhogar',
      'Shamash',
      'Shedinn',
      'Tarhun',
      'Torinn',
      // XGE 175-176
      'Adrex',
      'Arjhan',
      'Azzakh',
      'Salasar',
      'Barad ad',
      'Bharash',
      'Bidreked',
      'Dadalan',
      'Dazzazn',
      'Direcris',
      'Donaar',
      'Fax',
      'Gargax',
      'Ghesh',
      'Gorbundus',
      'Greethen ',
      'Heskan ',
      'Hirrathak ',
      'lldrex ',
      'Kaladan ',
      'Kerkad ',
      'Kiirith ',
      'Kriv ',
      'Maagog ',
      'Medrash ',
      'Mehen ',
      'Mozikth ',
      'Mreksh ',
      'Mugrunden ',
      'Nadarr ',
      'Nithther ',
      'Norkruuth ',
      'Nykkan ',
      'Pandjed ',
      'Patrin ',
      'Pijjirik ',
      'Quarethon ',
      'Rathkran ',
      'Rhogar ',
      'Rivaan ',
      'Sethrekar ',
      'Shamash ',
      'Shedinn',
      'Srorthen ',
      'Tarhun ',
      'Torinn ',
      'Trynnicus ',
      'Valorean ',
      'Vrondiss ',
      'Zedaar ',
    ],
    female: [
      // PHB
      'Akra',
      'Biri',
      'Daar',
      'Farideh',
      'Harann',
      'Havilar',
      'Jheri',
      'Kava',
      'Korinn',
      'Mishann',
      'Nala',
      'Perra',
      'Raiann',
      'Sora',
      'Surina',
      'Thava',
      'Uadjit',
      // XGE 175
      'Akra',
      'Aasathra',
      'Antrara',
      'Arava',
      'Biri',
      'Blendaeth',
      'Burana',
      'Chassath',
      'Daar',
      'Dentratha',
      'Doudra',
      'Driindar',
      'Eggren',
      'Farideh',
      'Findex',
      'Furrele',
      'Gesrethe',
      'Gilkass',
      'Harann',
      'Havilar',
      'Hethress',
      'Hillanot',
      'Jaxi',
      'Jezean',
      'Jheri',
      'Kadana',
      'Kava',
      'Korinn',
      'Megren',
      'Mijira',
      'Mishann',
      'Nala',
      'Nuthra',
      'Perra',
      'Pogranix',
      'Pyxrin',
      'Quespa',
      'Raiann',
      'Rezena',
      'Ruloth',
      'Saphara',
      'Savaran',
      'Sora',
      'Surina',
      'Synthrin',
      'Tatyan',
      'Thava',
      'Uadjit',
      'Vezera',
      'Zykroff',
    ],
    clan: [
      // PHB
      'Clethtinthiallor',
      'Daardendrian',
      'Delmirev',
      'Drachedandion',
      'Fenkenkabradon',
      'Kepeshkmolik',
      'Kerrhylon',
      'Kimbatuul',
      'Linxakasendalor',
      'Myastan',
      'Nemmonis',
      'Norixius',
      'Ophinshtalajiir',
      'Prexijandilin',
      'Shestendeliath',
      'Turnuroth',
      'Verthisathurgiesh',
      'Yarjerit',
      // XGE 175-176
      'Akambherylliax',
      'Argenthrixus',
      'Baharoosh',
      'Beryntolthropal',
      'Bhenkumbyrznaax',
      'Caavylteradyn',
      'Chumbyxirinnish',
      'Clethtinthiallor',
      'Daardendrian',
      'Delmirev',
      'Dhyrktelonis',
      'Ebynichtomonis',
      'Esstyrlynn',
      'Fharngnarthnost',
      'Ghaallixirn',
      'Grrrmmballhyst',
      'Gygazzylyshrift',
      'Hashphronyxadyn',
      'Hshhsstoroth',
      'lmbixtellrhyst',
      'Jerynomonis',
      'Jharthraxyn',
      'Kerrhylon',
      'Kimbatuul',
      'Lhamboldennish',
      'Linxakasendalor',
      'Mohradyllion',
      'Mysttan',
      'Nemmonis',
      'Norixius',
      'Ophinshtalajiir',
      'Orexijandilin',
      'Pfaphnyrennish',
      'Phrahdrandon',
      'Pyraxtallinost',
      'Qyxpahrgh',
      'Raghthroknaar',
      'Shestendeliath',
      'Skaarzborroosh',
      'Sumnarghthrysh',
      'Tiammanthyllish',
      'Turnuroth',
      'Umbyrphrael',
      'Vangdondalor',
      'Verthisathurgiesh',
      'Wivvyrholdalphiax',
      'Wystongjiir',
      'Xephyrbahnor',
      'Yarjerit',
      'Zzzxaaxthroth',
    ],
    child: [
      // PHB
      'Climber',
      'Earbender',
      'Leaper',
      'Pious',
      'Shieldbiter',
      'Zealous',
    ],
  },
};
