import { NameDefinitions } from '.';

type Type = 'male' | 'female';
type Part = 'male' | 'female' | 'clan';

export const dwarfNames: NameDefinitions<Type, Part> = {
  race: 'Dwarf',
  description: `A dwarf's name is granted by a clan elder, in accordance
    with tradition. Every proper dwarven name has been
    used and reused down through the generations. A
    dwarf's name belongs to the clan, not to the individual.
    A dwarf who misuses or brings shame to a clan name
    is stripped of the name and forbidden by law to use any
    dwarven name in its place.`,
  types: {
    male: {
      description: 'Male dwarf names',
      parts: ['male', 'clan'],
    },
    female: {
      description: 'Female dwarf names',
      parts: ['female', 'clan'],
    },
  },
  parts: {
    male: [
      // PHB
      'Adrik',
      'Alberich',
      'Baern',
      'Barendd',
      'Brottor',
      'Bruenor',
      'Dain',
      'Darrak',
      'Delg',
      'Eberk',
      'Einkil',
      'Fargrim',
      'Flint',
      'Gardain',
      'Harbek',
      'Kildrak',
      'Morgran',
      'Orsik',
      'Oskar',
      'Rangrim',
      'Rurik',
      'Taklinn',
      'Thoradin',
      'Thorin',
      'Tordek',
      'Traubon',
      'Travok',
      'Ulfgar',
      'Veit',
      'Vondal',
      // XGE 176
      'Adrik',
      'Alberich',
      'Baern',
      'Barendd',
      'Beloril',
      'Brottor',
      'Dain',
      'Dalgal',
      'Darrak',
      'Delg',
      'Duergath',
      'Dworic',
      'Eberk',
      'Einkil',
      'Elaim',
      'Erias',
      'Fallond',
      'Fargrim',
      'Gardain',
      'Gilthur',
      'Gimgen',
      'Gimurt',
      'Harbek',
      'Kildrak',
      'Kilvar',
      'Morgran',
      'Morkral',
      'Nalral',
      'Nordak',
      'Nuraval',
      'Oloric',
      'Olunt',
      'Orsik',
      'Oskar',
      'Rangrim',
      'Reirak',
      'Rurik',
      'Taklinn',
      'Thoradin',
      'Thorin',
      'Thradal',
      'Tordek',
      'Traubon',
      'Travok',
      'Ulfgar',
      'Uraim',
      'Veit',
      'Vonbin',
      'Vondal',
      'Whurbin',
    ],
    female: [
      // PHB
      'Amber',
      'Artin',
      'Audhild',
      'Bardryn',
      'Dagnal',
      'Diesa',
      'Eldeth',
      'Falkrunn',
      'Finellen',
      'Gunnloda',
      'Gurdis',
      'Helja',
      'Hlin',
      'Kathra',
      'Kristryd',
      'Ilde',
      'Liftrasa',
      'Mardred',
      'Riswynn',
      'Sann!',
      'Torbera',
      'Torgga',
      'Vistra',
      // XGE 176
      'Anbera',
      'Artin',
      'Audhild',
      'Balifra',
      'Barbena',
      'Bardryn',
      'Bolhild',
      'Dagnal',
      'Dariff',
      'Delre',
      'Diesa',
      'Eldeth',
      'Eridred',
      'Falkrunn',
      'Fallthra',
      'Finellen',
      'Gillydd',
      'Gunnloda',
      'Gurdis',
      'Helgret',
      'Helja',
      'Hlin',
      'llde',
      'Jarana',
      'Kathra',
      'Kilia',
      'Kristryd',
      'Liftrasa',
      'Marastyr',
      'Mardred',
      'Morana',
      'Nalaed',
      'Nora',
      'Nurkara',
      'Oriff',
      'Ovina',
      'Riswynn',
      'Sannl',
      'Therlin',
      'Thodris',
      'Torbera',
      'Tordrid',
      'Torgga',
      'Urshar',
      'Valida',
      'Vistra',
      'Vonana',
      'Werydd',
      'Whurdred',
      'Yurgunn ',
    ],
    clan: [
      // PHB
      'Balderk',
      'Battlehammer',
      'Brawnanvil',
      'Dankil',
      'Fireforge',
      'Frostbeard',
      'Gorunn',
      'Holderhek',
      'Ironfist',
      'Loderr',
      'Lutgehr',
      'Rumnaheim',
      'Strakeln',
      'Torunn',
      'Ungart',
      // XGE 176
      'Aranore',
      'Balderk',
      'Battlehammer',
      'Bigtoe',
      'Bloodkith',
      'Bofdann',
      'Brawnanvil',
      'Brazzik',
      'Broodfist',
      'Burrowfound',
      'Caebrek',
      'Daerdahk',
      'Dankil',
      'Daraln',
      'Deepdelver',
      'Durthane',
      'Eversharp',
      'Fallack',
      'Fireforge',
      'Foamtankard',
      'Frostbeard',
      'Glanhig',
      'Goblinbane',
      'Goldfinder',
      'Gorunn',
      'Graybeard',
      'Hammerstone',
      'Helcral',
      'Holderhek',
      'lronfist',
      'Loderr',
      'Lutgehr',
      'Morigak',
      'Orcfoe',
      'Rakankrak',
      'Ruby-Eye',
      'Rumnaheim',
      'Silveraxe',
      'Silverstone',
      'Steelfist',
      'Stoutale',
      'Strakeln',
      'Strongheart',
      'Thrahak',
      'Torevir',
      'Torunn',
      'Trollbleeder',
      'Trueanvil',
      'Trueblood',
      'Ungart',
    ],
  },
};
