import { NameDefinitions } from '.';

type Type = 'male' | 'female' | 'child';
type Part = 'male' | 'female' | 'family' | 'child';

export const elfNames: NameDefinitions<Type, Part> = {
  race: 'Elf',
  description: `Elves are considered children until they declare
  themselves adults, some time after the hundredth
  birthday, and before this period they are called
  by child names.
  On declaring adulthood, an elf selects an adult name,
  although those who knew him or her as a youngster
  might continue to use the child name. Each elf's adult
  name is a unique creation, though it might reflect
  the names of respected individuals or other family
  members. Little distinction exists between male
  names and female names; the groupings here reflect
  only general tendencies. In addition, every elf bears a
  family name, typically a combination of other Elvish
  words. Some elves traveling among humans translate
  their family names into Common, but others retain the
  Elvish version`,
  types: {
    male: {
      description: 'Male elf names',
      parts: ['male', 'family'],
    },
    female: {
      description: 'Female elf names',
      parts: ['female', 'family'],
    },
    child: {
      description: 'Child elf names',
      parts: ['child'],
    },
  },
  parts: {
    male: [
      // PHB
      'Adran',
      'Aelar',
      'Aramil',
      'Arannis',
      'Aust',
      'Beiro',
      'Berrian',
      'Carrie',
      'Enialis',
      'Erdan',
      'Erevan',
      'Galinndan',
      'Hadarai',
      'Heian',
      'Himo',
      'Immeral',
      'Ivellios',
      'Laucian',
      'Mindartis',
      'Paelias',
      'Peren',
      'Quarion',
      'Riardon',
      'Rolen',
      'Soveliss',
      'Thamior',
      'Tharivol',
      'Theren',
      'Varis',
      // XGE 177
      'Adran',
      'Aelar',
      'Aerdeth',
      'Ahvain',
      'Aramil',
      'Arannis',
      'Aust',
      'Azaki',
      'Beiro',
      'Berrian',
      'Caeldrim',
      'Carric',
      'Dayereth',
      'Dreali',
      'Efferil',
      'Eiravel',
      'Erwalis',
      'Erdan',
      'Erevan',
      'Fivin',
      'Galinndan',
      'Gennal',
      'Hadarai',
      'Halimath',
      'Heian',
      'Himo',
      'Immeral',
      'Ivellios',
      'Korfel',
      'Lamlis',
      'Laucian',
      'Lucan',
      'Mindartis',
      'Naal',
      'Nutae',
      'Paelias',
      'Peren',
      'Quarion',
      'Riardon',
      'Rolen',
      'Sovelis',
      'Suhnae',
      'Thamior',
      'Tharivol',
      'Theren',
      'Theriatis',
      'Thervan',
      'Uthemar',
      'Vanuath',
      'Varis',
    ],
    female: [
      // PHB
      'Adrie',
      'Althaea',
      'Anastrianna',
      'Andraste',
      'Antinua',
      'Bethrynna',
      'Birel',
      'Caelynn',
      'Drusilia',
      'Enna',
      'Felosial',
      'Ielenia',
      'Jelenneth',
      'Keyleth',
      'Leshanna',
      'Lia',
      'Meriele',
      'Mialee',
      'Naivara',
      'Quelenna',
      'Quillathe',
      'Sariel',
      'Shanairra',
      'Shava',
      'Silaqui',
      'Theirastra',
      'Thia',
      'Vadania',
      'Valanthe',
      'Xanaphia',
      // XGE 177
      'Adrie',
      'Ahinar',
      'Althaea',
      'Anastrianna',
      'Andraste',
      'Antinua',
      'Arara',
      'Baelitae',
      'Birel',
      'Caelynn',
      'Chaedi',
      'Claira',
      'Dara',
      'Drusilia',
      'Elama',
      'Enna',
      'Faral',
      'Felosial',
      'Hatae',
      'Ielenia',
      'Ilanis',
      'Irann',
      'Jarsali',
      'Jelenneth',
      'Keyleth',
      'Leshanna',
      'Lia',
      'Maiathah',
      'Malquis',
      'Meriele',
      'Mialee',
      'Myathethil',
      'Naivara',
      'Quelenna',
      'Quillathe',
      'Ridaro',
      'Sariel',
      'Shanairla',
      'Shava',
      'Silaqui',
      'Sumnes',
      'Theirastra',
      'Thiala',
      'Tiathque',
      'Traulam',
      'Vadania',
      'Valanthe',
      'Valna',
      'Xanaphia',
    ],
    family: [
      // PHB
      'Amakiir',
      'Amastacia',
      'Galanodel',
      'Holimion',
      'Ilphelkiir',
      'Liadon',
      'Meliamne',
      'Nallo',
      'Siannodel',
      'Xiloscient',
      // XGE 177-178
      'Aloro',
      'Amakiir',
      'Amastacia',
      'Ariessus',
      'Arnuanna',
      'Berevan',
      'Caerdonel',
      'Caphaxath',
      'Casilltenirra',
      'Cithereth',
      'Dalanthan',
      'Eathalena',
      'Erenaeth',
      'Ethanasath',
      'Fasharash',
      'Firahel',
      'Floshem',
      'Galanodel',
      'Goltorah',
      'Hanali',
      'Holimion',
      'Horineth',
      'lathrana',
      'llphelkiir',
      'lranapha',
      'Koehlanna',
      'Lathalas',
      'Liadon',
      'Meliamne',
      'Mellerelel',
      'Mystralath',
      'Nailo',
      'Netyoive',
      'Ofandrus',
      'Ostoroth',
      'Othronus',
      'Qualanthri',
      'Raethran',
      'Rothenel',
      'Selevarun',
      'Siannodel',
      'Suithrasas',
      'Sylvaranth',
      'Teinithra',
      'Tiltathana',
      'Wasanthi',
      'Withrethin',
      'Xiloscient',
      'Xistsrith',
      'Yaeldrin',
    ],
    child: [
      // PHB
      'Ara',
      'Bryn',
      'Del',
      'Eryn',
      'Faen',
      'Innil',
      'Lael',
      'Mella',
      'Naill',
      'Naeris',
      'Phann',
      'Rael',
      'Rinn',
      'Sai',
      'Syllin',
      'Thia',
      'Vall',
      // XGE 176-177
      'Ael',
      'Ang',
      'Ara',
      'Ari',
      'Arn',
      'Aym',
      'Broe',
      'Bryn',
      'Cael',
      'Cy',
      'Dae',
      'Del',
      'Eli',
      'Eryn',
      'Faen',
      'Fera',
      'Gael',
      'Gar',
      'lnnil',
      'Jar',
      'Kan',
      'Koeth',
      'Lael',
      'Lue',
      'Mai',
      'Mara',
      'Mella',
      'Mya',
      'Naeris',
      'Naill',
      'Nim',
      'Phann',
      'Py',
      'Rael',
      'Raer',
      'Ren',
      'Rinn',
      'Rua',
      'Sael',
      'Sai',
      'Sumi',
      'Syllin',
      'Ta',
      'Thia',
      'Tia',
      'Traki',
      'Vall',
      'Von',
      'Will',
      'Za',
    ],
  },
};
