import { NameDefinitions } from '.';

type Type = 'male' | 'female';
type Part = 'male' | 'female' | 'family';

export const halflingNames: NameDefinitions<Type, Part> = {
  race: 'Halfling',
  description: `A halfling has a given name, a family name, and possibly
  a nickname. Family names are often nicknames that
  stuck so tenaciously they have been passed down
  through the generations`,
  types: {
    male: {
      description: 'Male halfling names',
      parts: ['male', 'family'],
    },
    female: {
      description: 'Female halfling names',
      parts: ['female', 'family'],
    },
  },
  parts: {
    male: {
      markov: true,
      list: [
        // PHB
        'Alton',
        'Ander',
        'Cade',
        'Corrin',
        'Eldon',
        'Errich',
        'Finnan',
        'Garret',
        'Linda!',
        'Lyle',
        'Merrie',
        'Milo',
        'Osborn',
        'Perrin',
        'Reed',
        'Roscoe',
        'Wellby',
        // XGE 179
        'Alton',
        'Ander',
        'Bernie',
        'Bobbin',
        'Cade',
        'Callus',
        'Corrin',
        'Dannad',
        'Danniel',
        'Eddie',
        'Egart',
        'Eldon',
        'Errich',
        'Fildo',
        'Finnan',
        'Franklin',
        'Garret',
        'Garth',
        'Gilbert',
        'Gob',
        'Harol',
        'Igor',
        'Jasper',
        'Keith',
        'Kevin',
        'Lazam',
        'Lerry',
        'Lindal',
        'Lyle',
        'Merrie',
        'Mican',
        'Milo',
        'Morrin',
        'Nebin',
        'Nevil',
        'Osborn',
        'Ostran',
        'Oswalt',
        'Perrin',
        'Poppy',
        'Reed',
        'Roscoe',
        'Sam',
        'Shardon',
        'Tye',
        'Ulmo',
        'Wellby',
        'Wendel',
        'Wenner',
        'Wes',
      ],
    },
    female: {
      markov: true,
      list: [
        // PHB
        'Andry',
        'Bree',
        'Callie',
        'Cora',
        'Euphemia',
        'Jillian',
        'Kithri',
        'Lavinia',
        'Lidda',
        'Merla',
        'Nedda',
        'Paela',
        'Portia',
        'Seraphina',
        'Shaena',
        'Trym',
        'Vani',
        'Verna',
        // XGE 179
        'Alain',
        'Andry',
        'Anne',
        'Bella',
        'Blossom',
        'Bree',
        'Callie',
        'Chenna',
        'Cora',
        'Dee',
        'Dell',
        'Eida',
        'Eran',
        'Euphemia',
        'Georgina',
        'Gynnie',
        'Harriet',
        'Jasmine',
        'Jillian',
        'Jo',
        'Kithri',
        'Lavinia',
        'Lidda',
        'Maegan',
        'Marigold',
        'Merla',
        'Myria',
        'Nedda',
        'Nikki',
        'Nora',
        'Olivia',
        'Paela',
        'Pearl',
        'Pennie',
        'Philomena',
        'Portia',
        'Robbie',
        'Rose',
        'Sarai',
        'Seraphina',
        'Shaena',
        'Stacee',
        'Tawna',
        'Thea',
        'Trym',
        'Tyna',
        'Vani',
        'Verna',
        'Wella',
        'Willow',
      ],
    },
    family: {
      markov: true,
      list: [
        // PHB
        'Brushgather',
        'Goodbarrel',
        'Greenbottle',
        'High-hill',
        'Hilltopple',
        'Leagallow',
        'Tealeaf',
        'Thorngage',
        'Tosscobble',
        'Underbough',
        // XGE 179
        'Appleblossom',
        'Bigheart',
        'Brightmoon',
        'Brushgather',
        'Cherrycheeks',
        'Copperkettle',
        'Deephollow',
        'Elderberry',
        'Fastfoot',
        'Fatrabbit',
        'Glenfellow',
        'Goldfound',
        'Goodbarrel',
        'Goodearth',
        'Greenbottle',
        'Greenleaf',
        'High-hill',
        'Hilltopple',
        'Hogcollar',
        'Honeypot',
        'Jamjar',
        'Kettlewhistle',
        'Leagallow',
        'Littlefoot',
        'Nimblefingers',
        'Porridgepot',
        'Quickstep',
        'Reedfellow',
        'Shadowquick',
        'Silvereyes',
        'Smoothhands',
        'Stonebridge',
        'Stoutbridge',
        'Stoutman',
        'Strongbones',
        'Sunmeadow',
        'Swiftwhistle',
        'Tallfellow',
        'Tealeaf',
        'TellPenny',
        'Thistletop',
        'Thorngage',
        'Tosscobble',
        'Underbough',
        'Underfoot',
        'Warmwater',
        'Whispermouse',
        'Wildcloak',
        'Wildheart',
        'Wiseacre',
      ],
    },
  },
};
