import { NameDefinitions } from '.';

type Type = 'male' | 'female';
type Part = 'male' | 'female';

export const halfOrcNames: NameDefinitions<Type, Part> = {
  race: 'Half Orc',
  description: `Half-orcs usually have names appropriate to the culture
  in which they were raised. A half-orc who wants to fit in
  among humans might trade an orc name for a human
  name. Some half-orcs with human names decide to
  adopt a guttural orc name because they think it makes
  them more intimidating.`,
  types: {
    male: {
      description: 'Male half-orc names',
      parts: ['male'],
    },
    female: {
      description: 'Female half-orc names',
      parts: ['female'],
    },
  },
  parts: {
    male: [
      // PHB
      'Dench',
      'Feng',
      'Gell',
      'Henk',
      'Holg',
      'Imsh',
      'Keth',
      'Krusk',
      'Mhurren',
      'Ront',
      'Shump',
      'Thokk',
      // XGE 180
      'Argran',
      'Braak',
      'Brug',
      'Cagak',
      'Dench',
      'Dorn',
      'Oren',
      'Druuk',
      'Feng',
      'Gell',
      'Gnarsh',
      'Grumbar',
      'Gubrash',
      'Hagren',
      'Henk',
      'Hogar',
      'Holg',
      'lmsh',
      'Karash',
      'Karg',
      'Keth',
      'Korag',
      'Krusk',
      'Lubash',
      'Megged',
      'Mhurren',
      'Mord',
      'Morg',
      'Nil',
      'Nybarg',
      'Odorr',
      'Ohr',
      'Rendar',
      'Resh',
      'Ront',
      'Rrath',
      'Sark',
      'Scrag',
      'Sheggen',
      'Shump',
      'Tanglar',
      'Tarak',
      'Thar',
      'Thokk',
      'Trag',
      'Ugarth',
      'Varg',
      'Vilberg',
      'Yurk',
      'Zed ',
    ],
    female: [
      // PHB
      'Baggi',
      'Emen',
      'Engong',
      'Kansif',
      'Myev',
      'Neega',
      'Ovak',
      'Ownka',
      'Shautha',
      'Sutha',
      'Vola',
      'Volen',
      'Yevelda',
      // XGE 179
      'Arha',
      'Baggi',
      'Bendoo',
      'Bilga',
      'Brakka',
      'Creega',
      'Drenna',
      'Ekk',
      'Emen',
      'Engong',
      'Fistula',
      'Gaaki',
      'Gorga',
      'Grai',
      'Greeba',
      'Grigi',
      'Gynk',
      'Hrathy',
      'Huru',
      'llga',
      'Kabbarg',
      'Kansif',
      'Lagazi',
      'Lezre',
      'Murgen',
      'Murook',
      'Myev',
      'Nagrette',
      'Neega',
      'Nella',
      'Nogu',
      'Oolah',
      'Ootah',
      'Ovak',
      'Ownka',
      'Puyet',
      'Reeza',
      'Shautha',
      'Silgre',
      'Sutha',
      'Tagga',
      'Tawar',
      'Tomph',
      'Ubada',
      'Vanchu',
      'Vola',
      'Volen',
      'Vorka',
      'Yevelda',
      'Zagga',
    ],
  },
};
