import { NameDefinitions } from '.';

type Type = 'male' | 'female' | 'virtue';
type Part = 'male' | 'female' | 'virtue';

export const tieflingNames: NameDefinitions<Type, Part> = {
  race: 'Tiefling',
  description: `Tiefling names fall into three broad categories. Tieflings
  born into another culture typically have names reflective
  of that culture. Some have names derived from the
  Infernal language, passed down through generations,
  that reflect their fiendish heritage. And some younger
  tieflings, striving to find a place in the world, adopt a
  name that signifies a virtue or other concept and then
  try to embody that concept. For some, the chosen name
  is a noble quest. For others, it's a grim destiny. `,
  types: {
    male: {
      description: 'Male infernal names',
      parts: ['male'],
    },
    female: {
      description: 'Female infernal names',
      parts: ['female'],
    },
    virtue: {
      description: 'Virtue tiefling names',
      parts: ['virtue'],
    },
  },
  parts: {
    male: [
      // PHB
      'Akmenos',
      'Amnon',
      'Barakas',
      'Damakos',
      'Ekemon',
      'Iados',
      'Kairon',
      'Leucis',
      'Melech',
      'Mordai',
      'Morthos',
      'Pelaios',
      'Skamos',
      'Therai',
      // XGE 180
      'Abad',
      'Ahrim',
      'Akmen',
      'Amnon',
      'Andram',
      'Astar',
      'Balam',
      'Barakas',
      'Bat hin',
      'Cairn',
      'Chem',
      'Cimer',
      'Cressel',
      'Damakos',
      'Ekemon',
      'Euron',
      'Fenriz',
      'Forcas',
      'Habor',
      'lados',
      'Kairon',
      'Leucis',
      'Mamnen',
      'Mantus',
      'Marbas',
      'Melech',
      'Merihim',
      'Modean',
      'Mordai',
      'Mormo',
      'Morthos',
      'Nicor',
      'Nirgel',
      'Oriax',
      'Paymon',
      'Pelaios',
      'Purson',
      'Qemuel',
      'Raam',
      'Rimmon',
      'Sammal',
      'Skamos',
      'Tethren',
      'Thamuz',
      'Therai',
      'Valafar',
      'Vassago',
      'Xappan',
      'Zepar',
      'Zephan',
    ],
    female: [
      // PHB
      'Akta',
      'Anakis',
      'Bryseis',
      'Criella',
      'Damaia',
      'Ea',
      'Kallista',
      'Lerissa',
      'Makaria',
      'Nemeia',
      'Orianna',
      'Phelaia',
      'Rieta',
      // XGE 180
      'Akta',
      'Anakis',
      'Armara',
      'Astaro',
      'Aym',
      'Azza',
      'Beleth',
      'Bryseis',
      'Bune',
      'Criella',
      'Damaia',
      'Decarabia',
      'Ea',
      'Gadreel',
      'Gomory',
      'Hecat',
      'lshte',
      ')ezebeth',
      'Kali',
      'Kallista',
      'Kasdeya',
      'Lerissa',
      'Lilith',
      'Makaria',
      'Manea',
      'Markosian',
      'Mastema',
      'Naamah',
      'Nemeia',
      'Nija',
      'Orianna',
      'Osah',
      'Phelaia',
      'Prosperine',
      'Purah',
      'Pyra',
      'Rieta',
      'Ronobe',
      'Ronwe',
      'Seddit',
      'Seere',
      'Sekhmet',
      'Semyaza',
      'Shava',
      'Shax',
      'Sorath',
      'Uzza',
      'Vapula',
      'Vepar',
      'Verin',
    ],
    virtue: [
      // PHB
      'Art',
      'Carrion',
      'Chant',
      'Creed',
      'Despair',
      'Excellence',
      'Fear',
      'Glory',
      'Hope',
      'Ideal',
      'Music',
      'Nowhere',
      'Open',
      'Poetry',
      'Quest',
      'Random',
      'Reverence',
      'Sorrow',
      'Temerity',
      'Torment',
      'Weary',
      // XGE 180
      'Ambition',
      'Art',
      'Carrion',
      'Chant',
      'Creed',
      'Death',
      'Debauchery',
      'Despair',
      'Doom',
      'Doubt',
      'Dread',
      'Ecstasy',
      'Ennui',
      'Entropy',
      'Excellence',
      'Fear',
      'Glory',
      'Gluttony',
      'Grief',
      'Hate',
      'Hope',
      'Horror',
      'Ideal',
      'Ignominy',
      'Laughter',
      'Love',
      'Lust',
      'Mayhem',
      'Mockery',
      'Murder',
      'Muse',
      'Music',
      'Mystery',
      'Nowhere',
      'Open',
      'Pain',
      'Passion',
      'Poetry',
      'Quest',
      'Random',
      'Reverence',
      'Revulsion',
      'Sorrow',
      'Temerity',
      'Torment',
      'Tragedy',
      'Vice',
      'Virtue',
      'Weary',
      'Wit ',
    ],
  },
};
